In [1]:
#Gohel Sanjana D.
#216270307093

import numpy as np 
import pandas as pd

print("hello")

hello


In [2]:
#Gohel Sanjana D.
#216270307093

import numpy as py
import pandas as pd

a=10
b=20
sum=10+20
print(sum)

30


In [3]:
#Gohel Sanjana D.
#216270307093
#Write a NumPy program to implement to convert a list of numeric values into a one-dimensional NumPy array

import numpy as np

# Create a list of numeric values
numeric_list = [5,6,7,8,9]

# Convert the list to a NumPy array
numpy_array = np.array(numeric_list)

# Print the resulting NumPy array
print(numpy_array)




[5 6 7 8 9]


In [4]:
#Gohel Sanjana D.
#216270307093
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

import numpy as np

# Create an array of values ranging from 2 to 10
values = np.arange(2, 11)

# Reshape the array into a 3x3 matrix
matrix = values.reshape(3, 3)

# Print the resulting matrix
print(matrix)




[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
#Gohel Sanjana D.
#216270307093
#Write a NumPy program to create another shape from an array without changing its data (3*2 to 2*3) 
